services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=intro
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=tienda
    ports:
      - 5342:5342
    volumes:
      - ./psql_data:/var/lib/postgresql/data